package com.artezo.service;

import com.artezo.dto.request.ShiprocketOrderPayload;
import com.artezo.dto.request.ShiprocketWebhookPayload;

import java.util.Map;

/**
 * Handles the full Shiprocket Hot Checkout lifecycle:
 *
 *  1. createPendingOrder   — called by frontend /pre-checkout before SR redirect
 *  2. processShiprocketOrder — called by SR Custom Endpoint /order-sync after payment
 *  3. handleWebhookEvent   — called by SR Webhook for real-time status updates
 */
public interface SRCheckoutService {

    /**
     * Creates a PENDING SRPreCheckoutEntity so we track the attempt
     * even if the user abandons mid-checkout.
     *
     * @param orderRef unique ref generated by frontend (ORD-timestamp-XXXX)
     * @param body     raw request body from /pre-checkout (productId, qty, price etc.)
     */
    void createPendingOrder(String orderRef, Map<String, Object> body);

    /**
     * Called when SR fires to our Custom Endpoint after a successful order.
     * Responsibilities:
     *  - Find the SRPreCheckoutEntity by orderRef (payload.orderName())
     *  - Resolve product from DB using SKU / product id in the line item
     *  - Build and persist OrderEntity + OrderItemEntity (orderFlow = BUY_NOW)
     *  - Update SRPreCheckoutEntity.status = CONFIRMED, link .order
     *
     * @param payload deserialized SR order-sync POST body
     */
    void processShiprocketOrder(ShiprocketOrderPayload payload);

    /**
     * Called by SR Webhook for real-time events like ORDER_PLACED,
     * PAYMENT_SUCCESS, AWB_ASSIGNED, OUT_FOR_DELIVERY, DELIVERED etc.
     *
     * Updates OrderEntity.shippingStatus / paymentStatus accordingly.
     *
     * @param payload deserialized SR webhook body
     */
    void handleWebhookEvent(ShiprocketWebhookPayload payload);
}